---
- name: Ensure etc directory in place
  file:
    state: directory
    path: "{{ elastalert_etc_root }}"

- name: Ensure pre-reqs installed
  package:
    name: "{{ item }}"
  with_items: "{{ elastalert_pkgs }}"

- name: Establish system group
  group:
    name: "{{ elastalert_group }}"

- name: Establish system user
  user:
    name: "{{ elastalert_user }}"
    group: "{{ elastalert_group }}"
    shell: /bin/false
